"""Claude Code adapter — renders .claude/CLAUDE.md from a HarnessProfile.

Claude Code reads ``.claude/CLAUDE.md`` (or ``CLAUDE.md`` in the repo root)
at session start. Putting harness's profile output there means Claude
immediately knows what kind of project it's in, what commands are safe,
and what conventions to follow — with zero per-IDE config from the user.
"""

from __future__ import annotations

from pathlib import Path

from harness.profile import HarnessProfile

OUTPUTS = [".claude/CLAUDE.md"]


def render(profile: HarnessProfile, root: Path) -> list[Path]:
    out_dir = root / ".claude"
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / "CLAUDE.md"
    target.write_text(_compose(profile))
    return [target]


def _compose(p: HarnessProfile) -> str:
    cmds = []
    if p.test_command:
        cmds.append(f"- **Run tests**: `{p.test_command}`")
    if p.lint_command:
        cmds.append(f"- **Lint**: `{p.lint_command}`")
    if p.build_command:
        cmds.append(f"- **Build**: `{p.build_command}`")
    if p.dev_command:
        cmds.append(f"- **Dev server**: `{p.dev_command}`")
    cmds_block = "\n".join(cmds) if cmds else "_(none detected)_"

    conv = "\n".join(f"- {c}" for c in p.conventions) or "_(none)_"
    crit = "\n".join(f"- {c}" for c in p.success_criteria) or "_(none)_"
    forbid_paths = "\n".join(f"- `{c}`" for c in p.forbidden_paths) or "_(none)_"
    forbid_cmds = "\n".join(f"- `{c}`" for c in p.forbidden_commands) or "_(none)_"
    approval = "\n".join(f"- {c}" for c in p.requires_human_approval) or "_(none)_"
    envs = ", ".join(f"`{e}`" for e in p.required_env_vars) or "_(none)_"

    return f"""# {p.name}

> _Auto-generated by [harness](https://github.com/jcaiagent7143-ui/harnessforge) v{p.harness_version}._
> _Edit `.harness/profile.yaml` and run `harness sync` to regenerate; don't edit this file directly._

{p.description}

**Project type**: `{p.project_type}` · **Language**: `{p.primary_language}` · **Frameworks**: {", ".join(p.frameworks) or "_none detected_"}

---

## Commands you may run

{cmds_block}

## Conventions

{conv}

## What counts as success

{crit}

## Forbidden paths (never edit, never read for secrets)

{forbid_paths}

## Forbidden commands (refuse if asked)

{forbid_cmds}

## Always ask the user first before

{approval}

## Environment variables this project expects

{envs}

## Recommended MCP servers for this project

{chr(10).join(f"- `{m}`" for m in p.recommended_mcps) or "_(none)_"}

---

_If you're an LLM reading this: you're an engineer joining a team. Match the existing style, run the tests, and ask before doing anything destructive. The full machine-readable profile lives at `.harness/profile.yaml`._
"""
