"""OpenAI Codex CLI adapter — renders AGENTS.md from a HarnessProfile.

AGENTS.md is the standard OpenAI Codex CLI proposed; it's becoming a
broader convention. Aider also honors it. We write the canonical version
at the repo root.
"""

from __future__ import annotations

from pathlib import Path

from harness.profile import HarnessProfile

OUTPUTS = ["AGENTS.md"]


def render(profile: HarnessProfile, root: Path) -> list[Path]:
    target = root / "AGENTS.md"
    target.write_text(_compose(profile))
    return [target]


def _compose(p: HarnessProfile) -> str:
    fws = ", ".join(p.frameworks) if p.frameworks else "_none detected_"
    cmds = []
    if p.test_command:
        cmds.append(f"- Tests: `{p.test_command}`")
    if p.lint_command:
        cmds.append(f"- Lint: `{p.lint_command}`")
    if p.build_command:
        cmds.append(f"- Build: `{p.build_command}`")
    if p.dev_command:
        cmds.append(f"- Dev: `{p.dev_command}`")
    cmds_text = "\n".join(cmds) or "_(no automated commands detected)_"

    return f"""# AGENTS.md

_Generated by [harness](https://github.com/jcaiagent7143-ui/harness-kit) v{p.harness_version}. \
Source: `.harness/profile.yaml`._

## Project

**{p.name}** — {p.description}

- Type: {p.project_type}
- Primary language: {p.primary_language}
- Frameworks: {fws}

## Commands

{cmds_text}

## Conventions

{chr(10).join(f"- {c}" for c in p.conventions) or "_(none)_"}

## Definition of done

{chr(10).join(f"- {c}" for c in p.success_criteria) or "_(none)_"}

## Forbidden paths

{chr(10).join(f"- `{x}`" for x in p.forbidden_paths) or "_(none)_"}

## Forbidden commands

{chr(10).join(f"- `{x}`" for x in p.forbidden_commands) or "_(none)_"}

## Require human approval

{chr(10).join(f"- {x}" for x in p.requires_human_approval) or "_(none)_"}

## Environment variables

{", ".join(f"`{e}`" for e in p.required_env_vars) or "_(none)_"}

## Recommended MCP servers

{chr(10).join(f"- `{m}`" for m in p.recommended_mcps) or "_(none)_"}
"""
