"""Cursor adapter — renders .cursor/rules from a HarnessProfile."""

from __future__ import annotations

from pathlib import Path

from harness.profile import HarnessProfile

OUTPUTS = [".cursor/rules"]


def render(profile: HarnessProfile, root: Path) -> list[Path]:
    out_dir = root / ".cursor"
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / "rules"
    target.write_text(_compose(profile))
    return [target]


def _compose(p: HarnessProfile) -> str:
    lines = [
        f"# {p.name} — Cursor rules",
        "# Auto-generated by harness — edit .harness/profile.yaml and re-run `harness sync`.",
        "",
        f"You are working in `{p.name}`, a {p.project_type} written in {p.primary_language}.",
        f"Frameworks: {', '.join(p.frameworks) or 'none detected'}.",
        "",
        "## Always",
    ]
    lines += [f"- {c}" for c in p.conventions]
    lines += ["", "## Commands"]
    if p.test_command:
        lines.append(f"- Run tests: `{p.test_command}`")
    if p.lint_command:
        lines.append(f"- Lint: `{p.lint_command}`")
    if p.build_command:
        lines.append(f"- Build: `{p.build_command}`")
    lines += ["", "## Never"]
    lines += [f"- Touch: `{p}`" for p in p.forbidden_paths]
    lines += [f"- Run: `{c}`" for c in p.forbidden_commands]
    lines += ["", "## Ask first before"]
    lines += [f"- {a}" for a in p.requires_human_approval]
    lines += ["", "## Definition of done"]
    lines += [f"- {s}" for s in p.success_criteria]
    return "\n".join(lines) + "\n"
