"""Windsurf adapter — renders .windsurf/rules from a HarnessProfile.

Windsurf (Codeium's IDE) reads ``.windsurf/rules`` for repository-scoped
agent instructions. Format is plain markdown with sections — identical
shape to Cursor's ``.cursor/rules`` so we share the structural template
but write to the Windsurf-native path.
"""

from __future__ import annotations

from pathlib import Path

from harness.profile import HarnessProfile

OUTPUTS = [".windsurf/rules"]


def render(profile: HarnessProfile, root: Path) -> list[Path]:
    out_dir = root / ".windsurf"
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / "rules"
    target.write_text(_compose(profile))
    return [target]


def _compose(p: HarnessProfile) -> str:
    lines = [
        f"# {p.name} — Windsurf rules",
        "# Auto-generated by harness — edit .harness/profile.yaml and re-run `harness sync`.",
        "",
        f"You are working in `{p.name}`, a {p.project_type} written in {p.primary_language}.",
        f"Frameworks: {', '.join(p.frameworks) or 'none detected'}.",
        "",
        p.description,
        "",
        "## Always follow",
    ]
    lines += [f"- {c}" for c in p.conventions] or ["- _(none)_"]
    lines += ["", "## Commands you may run"]
    if p.test_command:
        lines.append(f"- Tests: `{p.test_command}`")
    if p.lint_command:
        lines.append(f"- Lint:  `{p.lint_command}`")
    if p.build_command:
        lines.append(f"- Build: `{p.build_command}`")
    if p.dev_command:
        lines.append(f"- Dev:   `{p.dev_command}`")
    lines += ["", "## Never touch"]
    lines += [f"- `{x}`" for x in p.forbidden_paths] or ["- _(none)_"]
    lines += ["", "## Never run"]
    lines += [f"- `{x}`" for x in p.forbidden_commands] or ["- _(none)_"]
    lines += ["", "## Always ask the user first before"]
    lines += [f"- {x}" for x in p.requires_human_approval] or ["- _(none)_"]
    lines += ["", "## What counts as done"]
    lines += [f"- {x}" for x in p.success_criteria] or ["- _(none)_"]
    lines += [
        "",
        "## Recommended MCP servers for this project",
    ]
    lines += [f"- `{m}`" for m in p.recommended_mcps] or ["- _(none)_"]
    lines += [
        "",
        "## Validation",
        "",
        "If `harness verify` is available, run it after non-trivial changes:",
        "```bash",
        "harness verify --json",
        "```",
        "Non-zero exit means a blueprint validator failed; read the JSON `messages` field.",
    ]
    return "\n".join(lines) + "\n"
